  server:
        port : 8888 
  spring:
      cloud:
          config:
              server:
                git:
                  #uri: ssh://localhost/config-repo
                  uri: file:///${user.home}/app-config-repo
                  clone-on-start: true
                      #username: arnav 
                      #password: sweety 
                      #force-pull: true 


